### ISSUE TITLE
Access token

### ISSUE THREAD

**Issue by tingofurro** [wxllow/whatnot#6]
Hey everyone,

Is there a way to obtain a permanent access_token, so that SMS/email verification can be bypassed for programmatic access?
If not, how long is the validity period of an access token?

Thank you for the cool library!
Philippe

**Comment by wxllow** [comment]
Hey, 

You can use `await whatnot.save_session()` and then `await whatnot.load_session()` to save and load your session! The session is saved to a `session.json` file in the current directory. 

You can also change or access the `whatnot.access_token` and `whatnot.user_id` variables if you prefer to save your session another way (both variables are strings btw)! You also need to change the headers after changing your access token, do so with `whatnot.transport.headers = {"Authorization": f"Bearer {whatnot.access_token}"}` 

I don't know how long the access tokens last but I've had bots using this API running for several months and haven't needed to re-login.

**Comment by tingofurro** [comment]
Oh, that's great to know, I assumed that it expired after a few days. Problem solved!
